# PostgreSQL profile (default)
spring.datasource.url=jdbc:postgresql://localhost:5432/dbdadi
spring.datasource.username=dbdadi
spring.datasource.password=dbdadi
spring.datasource.driver-class-name=org.postgresql.Driver
