# Oracle profile
# Add ojdbc11 dependency to pom.xml before using this profile
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=dbdadi
spring.datasource.password=dbdadi
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
