# DB2 profile
# Add db2jcc4 dependency to pom.xml before using this profile
spring.datasource.url=jdbc:db2://localhost:50000/dbdadi
spring.datasource.username=dbdadi
spring.datasource.password=dbdadi
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.jpa.database-platform=org.hibernate.dialect.DB2Dialect
